param(
    [int]$Port = 5111
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
Add-Type -AssemblyName System.Net.Http

$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$dbPath = Join-Path $root 'Data\full-acceptance.db'
$base = "http://127.0.0.1:$Port"
$project = Join-Path $root 'EPATA.BusinessLedger.csproj'
$uploadProbe = Join-Path $root 'Data\acceptance-upload-proof.txt'
$serverJob = $null

function Write-Step($message) {
    Write-Host "[acceptance] $message"
}

function Assert-True($condition, $message) {
    if (-not $condition) {
        throw $message
    }
}

function Assert-Close([decimal]$actual, [decimal]$expected, [decimal]$tolerance, $message) {
    if ([math]::Abs([decimal]$actual - [decimal]$expected) -gt $tolerance) {
        throw "$message Expected $expected, got $actual."
    }
}

function Invoke-Json($method, $path, $body = $null) {
    $uri = "$base$path"
    if ($null -eq $body) {
        return Invoke-RestMethod -Method $method -Uri $uri
    }

    return Invoke-RestMethod -Method $method -Uri $uri -ContentType 'application/json' -Body ($body | ConvertTo-Json -Depth 20)
}

function Invoke-Raw($method, $path) {
    $uri = "$base$path"
    try {
        return Invoke-WebRequest -Method $method -Uri $uri -UseBasicParsing
    } catch [System.Net.WebException] {
        if ($_.Exception.Response) {
            return [pscustomobject]@{
                StatusCode = [int]$_.Exception.Response.StatusCode
                Content = ''
                Headers = $_.Exception.Response.Headers
            }
        }
        throw
    }
}

function New-DocPayload($type, $status, $number, $paid, $customer) {
    @{
        docNumber = $number
        docType = $type
        status = $status
        customerName = $customer
        customerPhone = '973-555-1000'
        customerAddress = 'Acceptance Test Lane'
        customerEmail = "$($customer.Replace(' ', '.').ToLowerInvariant())@example.test"
        preparedFor = $customer
        projectName = "Acceptance $type"
        material = 'PLA'
        color = 'Black'
        infill = '20%'
        projectDescription = 'Acceptance workflow proof'
        projectNotes = 'Generated by full-acceptance.ps1'
        pageSize = 'A4'
        docDate = '2026-05-30'
        dueDate = '2026-06-13'
        subtotal = 999
        discountAmount = -25
        rushAmount = -4
        taxAmount = -8
        total = 1
        amountPaid = $paid
        balance = 12345
        pricingGuide = 'Acceptance'
        termsNotes = 'Acceptance terms'
        standardTurnaround = '5 days'
        rushTurnaround = '2 days'
        calcGrams = 10
        calcHours = 1
        calcDesignHours = 0.5
        calcSetupFee = 2
        calcPostFee = 3
        calcGramRate = 0.05
        calcHourRate = 3
        calcDesignRate = 25
        calcMinimum = 15
        calcDifficulty = 1
        calcRush = 0
        calcDiscount = 0
        calcTaxRate = 10
        lineItems = @(
            @{
                sortOrder = 0
                description = 'Widget print'
                details = 'Line item canonicalization'
                quantity = 2
                rate = 50
                amount = 999
            },
            @{
                sortOrder = 1
                description = 'Negative ignored'
                details = 'Should not reduce subtotal'
                quantity = -3
                rate = 99
                amount = -297
            }
        )
        json = '{}'
    }
}

function Assert-DocMoney($doc, $expectedPaid, $message) {
    Assert-Close ([decimal]$doc.subtotal) 100 0.01 "$message subtotal"
    Assert-Close ([decimal]$doc.discountAmount) 0 0.01 "$message discount"
    Assert-Close ([decimal]$doc.rushAmount) 0 0.01 "$message rush"
    Assert-Close ([decimal]$doc.taxAmount) 10 0.01 "$message tax"
    Assert-Close ([decimal]$doc.total) 110 0.01 "$message total"
    Assert-Close ([decimal]$doc.amountPaid) ([decimal]$expectedPaid) 0.01 "$message paid"
    Assert-Close ([decimal]$doc.balance) ([decimal](110 - $expectedPaid)) 0.01 "$message balance"
}

function Assert-EstimateMoney($doc, $message) {
    Assert-Close ([decimal]$doc.subtotal) 100 0.01 "$message subtotal"
    Assert-Close ([decimal]$doc.taxAmount) 10 0.01 "$message tax"
    Assert-Close ([decimal]$doc.total) 110 0.01 "$message total"
    Assert-Close ([decimal]$doc.amountPaid) 0 0.01 "$message estimate paid"
    Assert-Close ([decimal]$doc.balance) 0 0.01 "$message estimate balance"
}

function Assert-CrudRoundTrip($route, $payload, $updateField, $updatedValue) {
    $created = Invoke-Json POST "/api/$route" $payload
    Assert-True ($created.id -gt 0) "$route create did not return an id."
    $fetched = Invoke-Json GET "/api/$route/$($created.id)"
    Assert-True ($fetched.id -eq $created.id) "$route fetch by id returned the wrong record."

    $updatedPayload = @{}
    foreach ($p in $created.PSObject.Properties) {
        $updatedPayload[$p.Name] = $p.Value
    }
    $updatedPayload[$updateField] = $updatedValue
    $updated = Invoke-Json PUT "/api/$route/$($created.id)" $updatedPayload
    Assert-True ($updated.$updateField -eq $updatedValue) "$route update did not persist $updateField."

    Invoke-Json DELETE "/api/$route/$($created.id)" | Out-Null
    $archived = Invoke-Json GET "/api/$route/$($created.id)"
    Assert-True ($archived.isArchived -eq $true) "$route delete did not archive the record."

    Invoke-Json POST "/api/$route/$($created.id)/restore" | Out-Null
    $restored = Invoke-Json GET "/api/$route/$($created.id)"
    Assert-True ($restored.isArchived -eq $false) "$route restore did not unarchive the record."
    return $restored
}

function Upload-ProofFile {
    Set-Content -LiteralPath $uploadProbe -Value 'Acceptance proof upload content' -NoNewline
    $client = [System.Net.Http.HttpClient]::new()
    $content = [System.Net.Http.MultipartFormDataContent]::new()
    $bytes = [System.IO.File]::ReadAllBytes($uploadProbe)
    $fileContent = [System.Net.Http.ByteArrayContent]::new($bytes)
    $fileContent.Headers.ContentType = [System.Net.Http.Headers.MediaTypeHeaderValue]::Parse('text/plain')
    $content.Add($fileContent, 'file', 'acceptance-upload-proof.txt')
    $response = $client.PostAsync("$base/api/documents/upload", $content).GetAwaiter().GetResult()
    $text = $response.Content.ReadAsStringAsync().GetAwaiter().GetResult()
    if (-not $response.IsSuccessStatusCode) {
        throw "Document upload failed with $($response.StatusCode): $text"
    }
    return $text | ConvertFrom-Json
}

try {
    Write-Step 'Preparing disposable database'
    foreach ($path in @($dbPath, "$dbPath-shm", "$dbPath-wal", $uploadProbe)) {
        if (Test-Path -LiteralPath $path) {
            Remove-Item -LiteralPath $path -Force
        }
    }

    Write-Step "Starting app on $base"
    $serverJob = Start-Job -ScriptBlock {
        param($root, $project, $port, $dbPath)
        Set-Location $root
        dotnet run --no-build -c Release --no-launch-profile --project $project -- "App:Url=http://127.0.0.1:$port" "ConnectionStrings:DefaultConnection=Data Source=$dbPath" "App:OpenBrowserOnStart=false"
    } -ArgumentList $root, $project, $Port, $dbPath

    $ready = $false
    for ($i = 0; $i -lt 45; $i++) {
        Start-Sleep -Milliseconds 750
        try {
            $health = Invoke-Json GET '/api/health'
            if ($health.status -eq 'ok') {
                $ready = $true
                break
            }
        } catch {
        }
    }
    if (-not $ready) {
        $jobOutput = Receive-Job -Job $serverJob -Keep
        throw "App did not become ready. Job output: $jobOutput"
    }

    Write-Step 'Checking static shells and core endpoints'
    foreach ($path in @('/', '/index.html', '/css/site.css', '/js/app.js', '/invoice-builder/', '/invoice-builder/index.html', '/invoice-builder/css/app.css', '/invoice-builder/js/app.js', '/invoice-builder/js/builder.js', '/invoice-builder/js/records.js', '/invoice-builder/js/pdf.js')) {
        $response = Invoke-Raw GET $path
        Assert-True ($response.StatusCode -eq 200) "Static asset $path failed."
    }
    Invoke-Json GET '/api/dashboard' | Out-Null
    Invoke-Json GET '/api/tax-audit' | Out-Null
    Invoke-Json GET '/api/lookups' | Out-Null
    Invoke-Json GET '/api/app-info' | Out-Null

    Write-Step 'Checking admin/config endpoints'
    $config = Invoke-Json GET '/api/config'
    $config.businessName = 'EPATA Acceptance Ledger'
    $config.calcMinimum = 18
    $savedConfig = Invoke-Json PUT '/api/config' $config
    Assert-True ($savedConfig.businessName -eq 'EPATA Acceptance Ledger') 'Config save did not persist businessName.'
    $clearFailure = Invoke-Raw POST '/api/database/clear'
    Assert-True ($clearFailure.StatusCode -eq 400) 'Database clear should be blocked.'

    Write-Step 'Checking generic ledger CRUD routes'
    $party = Assert-CrudRoundTrip 'parties' @{ name='Acceptance Customer'; partyType='Both'; email='customer@example.test'; phone='973-555-0101'; city='Testville'; state='NJ'; country='United States'; notes='acceptance' } 'notes' 'updated party'
    Assert-CrudRoundTrip 'products' @{ name='Acceptance Product'; sku='ACC-001'; category='3D Printed Product'; material='PLA'; color='Black'; grams=-10; materialCostPerGram=-0.1; printHours=2; machineRatePerHour=3; packagingCost=-1; designMinutes=20; targetPrice=-5; notes='acceptance' } 'notes' 'updated product' | Out-Null
    Assert-CrudRoundTrip 'customer-jobs' @{ jobDate='2026-05-30'; customerName='Acceptance Customer'; platform='Direct'; jobNumber='JOB-ACC-001'; relatedInvoiceNumber='INV-ACC-001'; jobName='Acceptance Job'; jobType='Print'; status='Open'; productName='Acceptance Product'; material='PLA'; color='Black'; quoteAmount=-25; invoiceAmount=-40; amountPaid=-10; notes='acceptance' } 'status' 'Completed' | Out-Null
    $sale = Assert-CrudRoundTrip 'sales' @{ saleDate='2026-05-30'; platform='Direct'; orderNumber='ORD-ACC-001'; invoiceNumber=''; customerName='Acceptance Customer'; productName='Acceptance Product'; quantity=-1; itemSales=80; shippingCharged=5; salesTaxCollected=6.8; customerPaid=999; platformFees=-3; shippingLabelCost=-2; refunds=-4; estimatedCogs=-5; status='Paid'; includeInDashboard=$true; notes='acceptance' } 'notes' 'updated sale'
    Assert-Close ([decimal]$sale.customerPaid) 91.8 0.01 'Sale CRUD customer paid should be normalized.'
    Assert-CrudRoundTrip 'receivable-invoices' @{ invoiceNumber='AR-ACC-001'; invoiceDate='2026-05-30'; dueDate='2026-06-15'; customerName='Acceptance Customer'; projectName='AR Project'; status='Partial'; subtotal=100; discount=-12; rushFee=-4; taxRatePercent=10; salesTax=-7; invoiceTotal=1; amountPaid=-2; includeInCashReports=$true; notes='acceptance' } 'status' 'Paid' | Out-Null
    $bill = Assert-CrudRoundTrip 'bills' @{ vendorName='Acceptance Vendor'; billNumber='BILL-ACC-001'; billDate='2026-05-30'; dueDate='2026-06-30'; category='Supplies'; description='Acceptance bill'; amount=100; salesTax=7; total=1; amountPaid=-8; status='Partial'; paymentAccount='Checking'; taxDeductible=$true; notes='acceptance' } 'status' 'Paid'
    Assert-Close ([decimal]$bill.total) 107 0.01 'Bill total should normalize amount plus tax.'
    $expense = Assert-CrudRoundTrip 'expenses' @{ expenseDate='2026-05-30'; vendorName='Acceptance Vendor'; category='Supplies'; description='Acceptance expense'; paymentAccount='Checking'; amount=20; salesTax=2; total=1; receiptProof='proof'; taxBucket='COGS/Materials'; deductibleStatus='Yes'; businessUsePercent=150; countedExpense=$true; taxDeductible=$true; notes='acceptance' } 'notes' 'updated expense'
    Assert-Close ([decimal]$expense.total) 22 0.01 'Expense total should normalize amount plus tax.'
    Assert-Close ([decimal]$expense.businessUsePercent) 100 0.01 'Expense business use should clamp at 100.'
    Assert-CrudRoundTrip 'assets' @{ name='Acceptance Printer'; purchaseDate='2026-05-30'; vendorName='Bambu'; category='Equipment'; cost=-200; serialNumber='ACC123'; businessUsePercent=150; inServiceDate='2026-05-30'; taxTreatment='Section 179'; countedExpenseThisYear=$true; notes='acceptance' } 'notes' 'updated asset' | Out-Null
    Assert-CrudRoundTrip 'makerworld-rewards' @{ rewardDate='2026-05-30'; rewardType='Gift Card'; pointsChange=-100; giftCardAmount=-50; codeLast4='1234'; status='Available'; incomeStatus='Yes - Count as income'; notes='acceptance' } 'notes' 'updated makerworld' | Out-Null
    Assert-CrudRoundTrip 'audit-documents' @{ documentDate='2026-05-30'; documentType='Receipt'; relatedRecordType='Expense'; relatedRecordNumber='EXP-ACC'; fileName='acceptance.pdf'; filePathOrUrl='C:\acceptance.pdf'; notes='acceptance' } 'notes' 'updated audit doc' | Out-Null
    Assert-CrudRoundTrip 'business-accounts' @{ name='Acceptance Checking'; accountType='Checking'; institution='Acceptance Bank'; last4='1111'; openingBalance=-10; currentBalance=-5; isActive=$true; notes='acceptance' } 'notes' 'updated account' | Out-Null
    Assert-CrudRoundTrip 'action-items' @{ title='Acceptance action'; area='Tax'; priority='High'; dueDate='2026-06-01'; status='Open'; relatedRecord='ACC'; notes='acceptance' } 'status' 'Done' | Out-Null
    Assert-CrudRoundTrip 'settings' @{ key='AcceptanceSetting'; value='One'; notes='acceptance' } 'value' 'Two' | Out-Null

    Write-Step 'Checking proof/document intake upload'
    $upload = Upload-ProofFile
    Assert-True ($upload.count -eq 1) 'Document upload did not create one audit document.'
    Assert-True ($upload.documents[0].id -gt 0) 'Document upload did not return an audit document id.'
    Assert-True ($upload.documents[0].fileName -eq 'acceptance-upload-proof.txt') 'Document upload returned the wrong filename.'

    Write-Step 'Checking estimate and invoice builder workflows'
    $nextEstimate = Invoke-Json GET '/api/documents/next-number?type=ESTIMATE'
    Assert-True ($nextEstimate.number -like 'EST-*') 'Next estimate number should be EST-*.' 
    $estimate = Invoke-Json POST '/api/documents' (New-DocPayload 'ESTIMATE' 'Sent' $nextEstimate.number 500 'Acceptance Estimate Customer')
    Assert-EstimateMoney $estimate 'Estimate create'

    $duplicate = Invoke-Json POST "/api/documents/$($estimate.id)/duplicate"
    Assert-True ($duplicate.id -ne $estimate.id) 'Document duplicate reused source id.'
    Assert-True ($duplicate.docType -eq 'ESTIMATE') 'Estimate duplicate changed doc type.'
    Assert-EstimateMoney $duplicate 'Estimate duplicate'

    $invoiceFromEstimate = Invoke-Json POST "/api/invoice-documents/$($estimate.id)/convert-to-invoice"
    Assert-True ($invoiceFromEstimate.docType -eq 'INVOICE') 'Convert to invoice did not change doc type.'
    Assert-True ($invoiceFromEstimate.docNumber -like 'INV-*') 'Convert to invoice did not assign INV number.'
    Assert-DocMoney $invoiceFromEstimate 0 'Converted invoice'

    $nextInvoice = Invoke-Json GET '/api/invoice-documents/next-number?type=INVOICE'
    Assert-True ($nextInvoice.number -like 'INV-*') 'Next invoice number should be INV-*.' 
    $paidInvoice = Invoke-Json POST '/api/invoice-documents' (New-DocPayload 'INVOICE' 'Paid' $nextInvoice.number 110 'Acceptance Paid Customer')
    Assert-DocMoney $paidInvoice 110 'Paid invoice create'

    $sales = Invoke-Json GET '/api/sales?includeArchived=true'
    $paidSale = @($sales | Where-Object { $_.invoiceNumber -eq $paidInvoice.docNumber })[0]
    Assert-True ($null -ne $paidSale) 'Paid invoice did not sync to Sales.'
    Assert-Close ([decimal]$paidSale.itemSales) 100 0.01 'Paid invoice sale item sales allocation'
    Assert-Close ([decimal]$paidSale.salesTaxCollected) 10 0.01 'Paid invoice sale tax allocation'
    Assert-Close ([decimal]$paidSale.customerPaid) 110 0.01 'Paid invoice sale customer paid'

    $arRows = Invoke-Json GET '/api/receivable-invoices?includeArchived=true'
    $paidAr = @($arRows | Where-Object { $_.invoiceNumber -eq $paidInvoice.docNumber })[0]
    Assert-True ($null -ne $paidAr) 'Paid invoice did not sync to AR.'
    Assert-Close ([decimal]$paidAr.invoiceTotal) 110 0.01 'Paid invoice AR total'
    Assert-Close ([decimal]$paidAr.amountPaid) 110 0.01 'Paid invoice AR paid'

    $partialPayload = New-DocPayload 'INVOICE' 'Partial' 'INV-ACC-PARTIAL' 55 'Acceptance Partial Customer'
    $partialInvoice = Invoke-Json POST '/api/documents' $partialPayload
    Assert-DocMoney $partialInvoice 55 'Partial invoice create'
    $sales = Invoke-Json GET '/api/sales?includeArchived=true'
    $partialSale = @($sales | Where-Object { $_.invoiceNumber -eq $partialInvoice.docNumber })[0]
    Assert-Close ([decimal]$partialSale.itemSales) 50 0.01 'Partial invoice sale item sales allocation'
    Assert-Close ([decimal]$partialSale.salesTaxCollected) 5 0.01 'Partial invoice sale tax allocation'
    Assert-Close ([decimal]$partialSale.customerPaid) 55 0.01 'Partial invoice sale paid'

    $partialPayload.status = 'Void'
    $partialPayload.amountPaid = 0
    $voidInvoice = Invoke-Json PUT "/api/documents/$($partialInvoice.id)" $partialPayload
    Assert-Close ([decimal]$voidInvoice.amountPaid) 0 0.01 'Void invoice paid should be zero.'
    $sales = Invoke-Json GET '/api/sales?includeArchived=true'
    $voidSale = @($sales | Where-Object { $_.invoiceNumber -eq $partialInvoice.docNumber })[0]
    Assert-True ($voidSale.includeInDashboard -eq $false) 'Voiding invoice should hide synced Sale from dashboard.'

    Invoke-Json DELETE "/api/documents/$($duplicate.id)" | Out-Null
    $arRows = Invoke-Json GET '/api/receivable-invoices?includeArchived=true'
    Assert-True (-not (@($arRows | Where-Object { $_.invoiceNumber -eq $duplicate.docNumber -and -not $_.isArchived }).Count)) 'Deleted duplicate left active AR rows.'

    Invoke-Json GET '/api/documents/latest' | Out-Null
    $stats = Invoke-Json GET '/api/documents/stats'
    Assert-True ($stats.totalInvoices -ge 3) 'Document stats did not count created invoices.'
    Assert-True ($stats.totalInvoiced -ge 110) 'Document stats did not include active invoice totals.'

    Write-Step 'Checking legacy import failure path is clean'
    $legacy = Invoke-Json POST '/api/invoice-documents/import-from-legacy'
    Assert-True ($legacy.success -eq $false) 'Legacy import without old app should fail gracefully, not claim success.'

    Write-Step 'Checking exports and backups'
    foreach ($entity in @('parties', 'sales', 'customer-jobs', 'receivable-invoices', 'bills', 'expenses', 'products', 'assets', 'makerworld-rewards', 'audit-documents', 'business-accounts', 'action-items')) {
        $csv = Invoke-Raw GET "/api/export/$entity"
        Assert-True ($csv.StatusCode -eq 200) "CSV export failed for $entity."
        Assert-True ($csv.Content.Length -gt 10) "CSV export for $entity looked empty."
    }
    $backup = Invoke-Raw GET '/api/database/backup'
    Assert-True ($backup.StatusCode -eq 200) 'Database backup endpoint failed.'
    $systemBackup = Invoke-Raw POST '/api/system/backup'
    Assert-True ($systemBackup.StatusCode -eq 200) 'System backup endpoint failed.'
    Assert-True ($systemBackup.Content.Length -gt 100) 'System backup response looked empty.'

    Write-Step 'Checking dashboard and tax calculation outputs'
    $dashboard = Invoke-Json GET '/api/dashboard'
    Assert-True ($dashboard.kpis.grossReceipts -gt 0) 'Dashboard gross receipts should reflect acceptance sales.'
    Assert-True ($dashboard.kpis.estimatedNet -ne $null) 'Dashboard estimatedNet missing.'
    $taxAudit = Invoke-Json GET '/api/tax-audit'
    Assert-True ($null -ne $taxAudit.summary) 'Tax audit summary missing.'
    $highTaxIssues = @($taxAudit.issues | Where-Object { $_.severity -eq 'High' })
    if ($highTaxIssues.Count -gt 0) {
        Write-Host '[acceptance] High tax issues:'
        $highTaxIssues | ConvertTo-Json -Depth 5 | Write-Host
    }
    Assert-True ($highTaxIssues.Count -eq 0) 'Tax audit has high severity issues in disposable acceptance DB.'

    Write-Step 'Checking API aliases agree'
    $docsA = Invoke-Json GET '/api/documents'
    $docsB = Invoke-Json GET '/api/invoice-documents'
    Assert-True (@($docsA).Count -eq @($docsB).Count) 'Documents and invoice-documents aliases returned different counts.'

    Write-Step 'Acceptance suite passed'
} catch {
    if ($serverJob) {
        $jobOutput = Receive-Job -Job $serverJob -Keep -ErrorAction SilentlyContinue
        if ($jobOutput) {
            Write-Host '[acceptance] Server output before failure:'
            Write-Host $jobOutput
        }
    }
    throw
} finally {
    if ($serverJob) {
        Stop-Job -Job $serverJob -ErrorAction SilentlyContinue | Out-Null
        Receive-Job -Job $serverJob -ErrorAction SilentlyContinue | Out-Null
        Remove-Job -Job $serverJob -Force -ErrorAction SilentlyContinue | Out-Null
    }

    foreach ($path in @($uploadProbe)) {
        if (Test-Path -LiteralPath $path) {
            Remove-Item -LiteralPath $path -Force
        }
    }
    Get-ChildItem -LiteralPath (Join-Path $root 'UploadedDocs') -Filter '*acceptance-upload-proof.txt' -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue
}
