param(
    [int]$Port = 5111
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
Add-Type -AssemblyName System.Net.Http

$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$dbPath = Join-Path $root 'Data\full-acceptance.db'
$base = "http://127.0.0.1:$Port"
$project = Join-Path $root 'EPATA.BusinessLedger.csproj'
$builtDll = @(
    Join-Path $root 'bin\Release\net10.0\EPATA.BusinessLedger.dll'
    Join-Path $root 'obj\verify-build\EPATA.BusinessLedger.dll'
) | Where-Object { Test-Path -LiteralPath $_ } | Sort-Object { (Get-Item -LiteralPath $_).LastWriteTimeUtc } -Descending | Select-Object -First 1
$uploadProbe = Join-Path $root 'Data\acceptance-upload-proof.txt'
$aiDocxProbe = Join-Path $root 'Data\acceptance-ai-source.docx'
$aiPdfProbe = Join-Path $root 'Data\acceptance-ai-source.pdf'
$serverJob = $null

function Write-Step($message) {
    Write-Host "[acceptance] $message"
}

function Assert-True($condition, $message) {
    if (-not $condition) {
        throw $message
    }
}

function Assert-Close([decimal]$actual, [decimal]$expected, [decimal]$tolerance, $message) {
    if ([math]::Abs([decimal]$actual - [decimal]$expected) -gt $tolerance) {
        throw "$message Expected $expected, got $actual."
    }
}

function Invoke-Json($method, $path, $body = $null) {
    $uri = "$base$path"
    if ($null -eq $body) {
        return Invoke-RestMethod -Method $method -Uri $uri
    }

    return Invoke-RestMethod -Method $method -Uri $uri -ContentType 'application/json' -Body ($body | ConvertTo-Json -Depth 20)
}

function Invoke-Raw($method, $path) {
    $uri = "$base$path"
    return Invoke-WebRequest -Method $method -Uri $uri -UseBasicParsing -SkipHttpErrorCheck
}

function New-DocPayload($type, $status, $number, $paid, $customer) {
    @{
        docNumber = $number
        docType = $type
        status = $status
        customerName = $customer
        customerPhone = '973-555-1000'
        customerAddress = 'Acceptance Test Lane'
        customerEmail = "$($customer.Replace(' ', '.').ToLowerInvariant())@example.test"
        preparedFor = $customer
        projectName = "Acceptance $type"
        material = 'PLA'
        color = 'Black'
        infill = '20%'
        projectDescription = 'Acceptance workflow proof'
        projectNotes = 'Generated by full-acceptance.ps1'
        pageSize = 'A4'
        docDate = '2026-05-30'
        dueDate = '2026-06-13'
        subtotal = 999
        discountAmount = -25
        rushAmount = -4
        taxAmount = -8
        total = 1
        amountPaid = $paid
        balance = 12345
        paymentMethod = 'Zelle'
        pricingGuide = 'Acceptance'
        termsNotes = 'Acceptance terms'
        standardTurnaround = '5 days'
        rushTurnaround = '2 days'
        calcGrams = 10
        calcHours = 1
        calcDesignHours = 0.5
        calcSetupFee = 2
        calcPostFee = 3
        calcGramRate = 0.05
        calcHourRate = 3
        calcDesignRate = 25
        calcMinimum = 15
        calcDifficulty = 1
        calcRush = 0
        calcDiscount = 0
        calcTaxRate = 10
        lineItems = @(
            @{
                sortOrder = 0
                description = 'Widget print'
                details = 'Line item canonicalization'
                quantity = 2
                rate = 50
                amount = 999
            },
            @{
                sortOrder = 1
                description = 'Negative ignored'
                details = 'Should not reduce subtotal'
                quantity = -3
                rate = 99
                amount = -297
            }
        )
        json = '{}'
    }
}

function Assert-DocMoney($doc, $expectedPaid, $message) {
    Assert-Close ([decimal]$doc.subtotal) 100 0.01 "$message subtotal"
    Assert-Close ([decimal]$doc.discountAmount) 0 0.01 "$message discount"
    Assert-Close ([decimal]$doc.rushAmount) 0 0.01 "$message rush"
    Assert-Close ([decimal]$doc.taxAmount) 10 0.01 "$message tax"
    Assert-Close ([decimal]$doc.total) 110 0.01 "$message total"
    Assert-Close ([decimal]$doc.amountPaid) ([decimal]$expectedPaid) 0.01 "$message paid"
    Assert-Close ([decimal]$doc.balance) ([decimal](110 - $expectedPaid)) 0.01 "$message balance"
}

function Assert-EstimateMoney($doc, $message) {
    Assert-Close ([decimal]$doc.subtotal) 100 0.01 "$message subtotal"
    Assert-Close ([decimal]$doc.taxAmount) 10 0.01 "$message tax"
    Assert-Close ([decimal]$doc.total) 110 0.01 "$message total"
    Assert-Close ([decimal]$doc.amountPaid) 0 0.01 "$message estimate paid"
    Assert-Close ([decimal]$doc.balance) 0 0.01 "$message estimate balance"
}

function Assert-CrudRoundTrip($route, $payload, $updateField, $updatedValue) {
    $created = Invoke-Json POST "/api/$route" $payload
    Assert-True ($created.id -gt 0) "$route create did not return an id."
    $fetched = Invoke-Json GET "/api/$route/$($created.id)"
    Assert-True ($fetched.id -eq $created.id) "$route fetch by id returned the wrong record."

    $updatedPayload = @{}
    foreach ($p in $created.PSObject.Properties) {
        $updatedPayload[$p.Name] = $p.Value
    }
    $updatedPayload[$updateField] = $updatedValue
    $updated = Invoke-Json PUT "/api/$route/$($created.id)" $updatedPayload
    Assert-True ($updated.$updateField -eq $updatedValue) "$route update did not persist $updateField."

    Invoke-Json DELETE "/api/$route/$($created.id)" | Out-Null
    $archived = Invoke-Json GET "/api/$route/$($created.id)"
    Assert-True ($archived.isArchived -eq $true) "$route delete did not archive the record."

    Invoke-Json POST "/api/$route/$($created.id)/restore" | Out-Null
    $restored = Invoke-Json GET "/api/$route/$($created.id)"
    Assert-True ($restored.isArchived -eq $false) "$route restore did not unarchive the record."
    return $restored
}

function Upload-ProofFile {
    Set-Content -LiteralPath $uploadProbe -Value 'Acceptance proof upload content' -NoNewline
    $client = [System.Net.Http.HttpClient]::new()
    $content = [System.Net.Http.MultipartFormDataContent]::new()
    $bytes = [System.IO.File]::ReadAllBytes($uploadProbe)
    $fileContent = [System.Net.Http.ByteArrayContent]::new($bytes)
    $fileContent.Headers.ContentType = [System.Net.Http.Headers.MediaTypeHeaderValue]::Parse('text/plain')
    $content.Add($fileContent, 'file', 'acceptance-upload-proof.txt')
    $response = $client.PostAsync("$base/api/documents/upload", $content).GetAwaiter().GetResult()
    $text = $response.Content.ReadAsStringAsync().GetAwaiter().GetResult()
    if (-not $response.IsSuccessStatusCode) {
        throw "Document upload failed with $($response.StatusCode): $text"
    }
    return $text | ConvertFrom-Json
}

function Invoke-AiEstimateUpload {
    $client = [System.Net.Http.HttpClient]::new()
    $content = [System.Net.Http.MultipartFormDataContent]::new()
    $content.Add([System.Net.Http.StringContent]::new("- 2x Custom keychains - `$18 each`n- 1x Replacement part - `$27"), 'sourceText')
    $content.Add([System.Net.Http.StringContent]::new('acceptance mixed sources'), 'sourceName')
    $imageContent = [System.Net.Http.ByteArrayContent]::new([byte[]](1, 2, 3, 4))
    $imageContent.Headers.ContentType = [System.Net.Http.Headers.MediaTypeHeaderValue]::Parse('image/png')
    $content.Add($imageContent, 'files', 'reference-view.png')
    $response = $client.PostAsync("$base/api/ai/estimate-draft/upload", $content).GetAwaiter().GetResult()
    $text = $response.Content.ReadAsStringAsync().GetAwaiter().GetResult()
    if (-not $response.IsSuccessStatusCode) {
        throw "AI estimate upload failed with $($response.StatusCode): $text"
    }
    return $text | ConvertFrom-Json
}

function New-AcceptanceDocx {
    param([string]$Path)
    Add-Type -AssemblyName System.IO.Compression
    $stream = [System.IO.File]::Open($Path, [System.IO.FileMode]::Create)
    try {
        $archive = [System.IO.Compression.ZipArchive]::new($stream, [System.IO.Compression.ZipArchiveMode]::Create, $false)
        try {
            $entry = $archive.CreateEntry('word/document.xml')
            $writer = [System.IO.StreamWriter]::new($entry.Open())
            try {
                $writer.Write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Customer: Acceptance DOCX Customer</w:t></w:r></w:p><w:p><w:r><w:t>- 2x DOCX bracket - $31</w:t></w:r></w:p></w:body></w:document>')
            } finally {
                $writer.Dispose()
            }
        } finally {
            $archive.Dispose()
        }
    } finally {
        $stream.Dispose()
    }
}

function Invoke-AiEstimateDocumentUpload {
    New-AcceptanceDocx -Path $aiDocxProbe
    [System.IO.File]::WriteAllText($aiPdfProbe, '%PDF-1.4 BT (PDF custom sign request) Tj ET %%EOF', [System.Text.Encoding]::Latin1)
    $client = [System.Net.Http.HttpClient]::new()
    $content = [System.Net.Http.MultipartFormDataContent]::new()
    $content.Add([System.Net.Http.StringContent]::new('acceptance PDF and DOCX sources'), 'sourceName')
    foreach ($spec in @(
        @{ Path = $aiDocxProbe; Type = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'; Name = 'customer-request.docx' },
        @{ Path = $aiPdfProbe; Type = 'application/pdf'; Name = 'customer-reference.pdf' }
    )) {
        $fileContent = [System.Net.Http.ByteArrayContent]::new([System.IO.File]::ReadAllBytes($spec.Path))
        $fileContent.Headers.ContentType = [System.Net.Http.Headers.MediaTypeHeaderValue]::Parse($spec.Type)
        $content.Add($fileContent, 'files', $spec.Name)
    }
    $response = $client.PostAsync("$base/api/ai/estimate-draft/upload", $content).GetAwaiter().GetResult()
    $text = $response.Content.ReadAsStringAsync().GetAwaiter().GetResult()
    if (-not $response.IsSuccessStatusCode) {
        throw "AI document estimate upload failed with $($response.StatusCode): $text"
    }
    return $text | ConvertFrom-Json
}

try {
    Write-Step 'Preparing disposable database'
    foreach ($path in @($dbPath, "$dbPath-shm", "$dbPath-wal", $uploadProbe, $aiDocxProbe, $aiPdfProbe)) {
        if (Test-Path -LiteralPath $path) {
            Remove-Item -LiteralPath $path -Force
        }
    }

    Write-Step "Starting app on $base"
    $serverJob = Start-Job -ScriptBlock {
        param($root, $project, $builtDll, $port, $dbPath)
        Set-Location $root
        if (Test-Path -LiteralPath $builtDll) {
            dotnet $builtDll "App:Url=http://127.0.0.1:$port" "ConnectionStrings:DefaultConnection=Data Source=$dbPath" "App:OpenBrowserOnStart=false"
        } else {
            dotnet run --no-build -c Release --no-launch-profile --project $project -- "App:Url=http://127.0.0.1:$port" "ConnectionStrings:DefaultConnection=Data Source=$dbPath" "App:OpenBrowserOnStart=false"
        }
    } -ArgumentList $root, $project, $builtDll, $Port, $dbPath

    $ready = $false
    for ($i = 0; $i -lt 45; $i++) {
        Start-Sleep -Milliseconds 750
        try {
            $health = Invoke-Json GET '/api/health'
            if ($health.status -eq 'ok') {
                $ready = $true
                break
            }
        } catch {
        }
    }
    if (-not $ready) {
        $jobOutput = Receive-Job -Job $serverJob -Keep
        throw "App did not become ready. Job output: $jobOutput"
    }

    Write-Step 'Checking static shells and core endpoints'
    foreach ($path in @('/', '/index.html', '/css/site.css', '/js/app.js', '/invoice-builder/', '/invoice-builder/index.html', '/invoice-builder/css/app.css', '/invoice-builder/js/app.js', '/invoice-builder/js/builder.js', '/invoice-builder/js/records.js', '/invoice-builder/js/pdf.js')) {
        $response = Invoke-Raw GET $path
        Assert-True ($response.StatusCode -eq 200) "Static asset $path failed."
    }
    $appJs = (Invoke-Raw GET '/js/app.js').Content
    Assert-True ($appJs -match 'function assistanceIndicator') 'Assistance source indicator is missing from the app shell.'
    Assert-True ($appJs -match 'Automatic fallback while Local AI is unavailable') 'Local AI fallback indicator is missing.'
    Invoke-Json GET '/api/dashboard' | Out-Null
    Invoke-Json GET '/api/tax-audit' | Out-Null
    $taxProfile = Invoke-Json GET '/api/tax-profile'
    Assert-True ($taxProfile.state -eq 'New Jersey') 'Tax profile did not default to New Jersey.'
    $taxProfile.entityType = 'Single-member LLC / Schedule C'
    $taxProfile.formationMonth = 5
    $taxProfile.njSalesTaxRegistration = 'Registered'
    $taxProfile.usesVehicle = 'Yes'
    $taxProfile.businessMileageRate = 0.70
    $savedTaxProfile = Invoke-Json PUT '/api/tax-profile' $taxProfile
    Assert-True ($savedTaxProfile.formationMonth -eq 5) 'Tax profile formation month did not save.'
    $taxCalendar = Invoke-Json POST '/api/tax-calendar/generate?year=2026'
    Assert-True (@($taxCalendar).Count -ge 10) 'Tax calendar generation did not create the expected obligation set.'
    Assert-True (@($taxCalendar | Where-Object { $_.title -like '*annual report*' -and ([datetime]$_.dueDate).Month -eq 5 }).Count -eq 1) 'NJ annual report did not use the configured formation month.'
    $taxSummary = Invoke-Json GET '/api/tax-summary?year=2026'
    Assert-True ($taxSummary.taxYear -eq 2026) 'Tax summary returned the wrong year.'
    Invoke-Json GET '/api/lookups' | Out-Null
    Invoke-Json GET '/api/app-info' | Out-Null
    $localAiStatus = Invoke-Json GET '/api/ai/local/status'
    Assert-True ($localAiStatus.localOnly -eq $true) 'Local AI status did not enforce its local-only boundary.'
    Assert-True ($localAiStatus.baseUrl -eq 'http://127.0.0.1:1234') 'Local AI status did not use the safe default loopback URL.'
    $savedLocalAiSettings = Invoke-Json PUT '/api/ai/local/settings' @{
        baseUrl = 'http://localhost:1234'
        modelPath = $null
        modelIdentifier = 'acceptance-local'
        contextLength = 4096
        idleUnloadSeconds = 600
    }
    Assert-True ($savedLocalAiSettings.baseUrl -eq 'http://localhost:1234') 'Local AI settings did not save a loopback URL.'
    Assert-True ($savedLocalAiSettings.modelIdentifier -eq 'acceptance-local') 'Local AI settings did not save the model identifier.'
    $invalidLocalAiSettings = Invoke-WebRequest -Method PUT -Uri "$base/api/ai/local/settings" -ContentType 'application/json' -Body (@{
        baseUrl = 'https://example.com'
        modelPath = $null
        modelIdentifier = 'unsafe'
        contextLength = 4096
        idleUnloadSeconds = 600
    } | ConvertTo-Json) -SkipHttpErrorCheck
    Assert-True ($invalidLocalAiSettings.StatusCode -eq 400) 'Local AI settings accepted a non-loopback URL.'
    $catalogProduct = Invoke-Json POST '/api/products' @{
        name = 'Acceptance Catalog Widget'
        sku = 'AI-CATALOG-001'
        category = '3D Printed Product'
        material = 'PETG'
        color = 'Blue'
        grams = 100
        materialCostPerGram = 0.04
        printHours = 2
        machineRatePerHour = 3
        packagingCost = 2
        designMinutes = 30
        targetPrice = 40
        notes = 'Saved product costing acceptance test'
    }
    $aiStatus = Invoke-Json GET '/api/ai/estimate/status'
    Assert-True ($aiStatus.instructionsPath -like '*AiEstimateInstructions.json') 'AI estimate status did not report the editable instructions path.'
    Assert-True (@($aiStatus.supportedUploads) -contains '.png') 'AI estimate status did not report picture upload support.'
    Assert-True (@($aiStatus.supportedUploads) -contains '.pdf') 'AI estimate status did not report PDF upload support.'
    Assert-True (@($aiStatus.supportedUploads) -contains '.docx') 'AI estimate status did not report DOCX upload support.'
    Assert-True ($aiStatus.limits.maxCombinedTextCharacters -eq 500000) 'AI estimate status did not report the expanded text limit.'
    Assert-True ($aiStatus.builderPath -like '*invoice-builder*index.html') 'AI estimate status did not report the ingested HTML builder path.'
    Assert-True (@($aiStatus.builderFields) -contains 'grams') 'AI estimate status did not ingest calculator fields from the HTML builder.'
    Assert-True (@($aiStatus.builderFields) -contains 'termsNotes') 'AI estimate status did not ingest terms fields from the HTML builder.'
    Assert-True ($aiStatus.productCatalogCount -ge 1) 'AI estimate status did not report the saved product/cost catalog.'
    $aiDraft = Invoke-Json POST '/api/ai/estimate-draft' @{
        sourceName = 'acceptance-email.txt'
        sourceText = "From: Jane Customer`nSubject: Replacement bracket`nPlease make 3 black PETG replacement parts, 40mm x 20mm x 10mm. My phone is 973-555-0123."
    }
    Assert-True ($aiDraft.prefill.docType -eq 'ESTIMATE') 'AI estimate intake did not return an estimate draft.'
    Assert-True (@($aiDraft.prefill.lineItems).Count -gt 0) 'AI estimate intake did not return a line item.'
    Assert-True ($aiDraft.prefill.customerPhone -eq '(973) 555-0123') 'AI estimate intake did not normalize the customer phone.'
    Assert-True ($aiDraft.prefill.projectNotes -like '*ASSISTANCE:*') 'AI estimate intake did not add durable assistance provenance to Project Notes.'
    Assert-True ($aiDraft.prefill.termsNotes.Length -gt 20) 'AI estimate intake did not fill estimate terms.'
    Assert-True ($aiDraft.prefill.standardTurnaround.Length -gt 10) 'AI estimate intake did not fill standard turnaround.'
    Assert-True ($aiDraft.prefill.calcGramRate -eq 0.05) 'AI estimate intake did not fill the calculator material rate.'
    Assert-True ($aiDraft.prefill.assistanceSource -eq 'LOCAL RULES') 'AI estimate fallback did not identify its builder assistance source.'
    Assert-True ($aiDraft.executionReceipt.engine -eq 'LOCAL RULES') 'AI estimate fallback did not return a Local Rules execution receipt.'
    Assert-True ($aiDraft.executionReceipt.usedAi -eq $false) 'AI estimate fallback execution receipt incorrectly claimed model AI use.'
    Assert-True ($aiDraft.executionReceipt.totalTokens -eq $null) 'AI estimate fallback execution receipt incorrectly reported model tokens.'
    Assert-True ($aiDraft.prefill.projectNotes -like '*LOCAL RULES RECEIPT:*') 'AI estimate fallback did not preserve its execution receipt in Project Notes.'
    $aiPricedDraft = Invoke-Json POST '/api/ai/estimate-draft' @{
        sourceName = 'acceptance-priced-request.txt'
        sourceText = "Customer: Price Check Customer`nSubject: PETG enclosure`nUse black PETG. Material: 120 grams. Print time: 6 hours. Design time: 1 hour. Setup fee: `$5. Post-processing: `$4. Material rate: `$0.05 per gram. Machine rate: `$3. Design rate: `$25. Minimum: `$15. Rush: 25%. Discount: `$2. Tax: 6.625%."
    }
    Assert-True ($aiPricedDraft.pricing.usedCalculatorInputs -eq $true) 'AI estimate intake did not use supplied calculator inputs.'
    Assert-Close ([decimal]$aiPricedDraft.pricing.material) 6 0.01 'AI estimate material calculation'
    Assert-Close ([decimal]$aiPricedDraft.pricing.machine) 18 0.01 'AI estimate machine-time calculation'
    Assert-Close ([decimal]$aiPricedDraft.pricing.design) 25 0.01 'AI estimate design calculation'
    Assert-Close ([decimal]$aiPricedDraft.pricing.lineSubtotal) 58 0.01 'AI estimate deterministic line subtotal'
    Assert-Close ([decimal]$aiPricedDraft.pricing.total) 75.17 0.01 'AI estimate deterministic quote total'
    Assert-True (@($aiPricedDraft.prefill.lineItems | Where-Object { $_.description -eq 'Material usage' }).Count -eq 1) 'AI estimate did not build the material-cost line item.'
    Assert-True ($aiPricedDraft.prefill.projectNotes -like '*PRICING BASIS:*') 'AI estimate did not add durable pricing provenance.'
    $aiCatalogDraft = Invoke-Json POST '/api/ai/estimate-draft' @{
        sourceName = 'saved-product-request.txt'
        sourceText = 'Please quote one Acceptance Catalog Widget.'
    }
    Assert-True ($aiCatalogDraft.prefill.material -eq 'PETG') 'AI estimate did not use the saved product material.'
    Assert-Close ([decimal]$aiCatalogDraft.prefill.calcGrams) 100 0.01 'AI estimate saved product grams'
    Assert-Close ([decimal]$aiCatalogDraft.pricing.total) 40 0.01 'AI estimate saved product target-price floor'
    Assert-True (@($aiCatalogDraft.warnings | Where-Object { $_ -like '*Saved product costing was applied*' }).Count -eq 1) 'AI estimate did not disclose saved product costing use.'
    Invoke-Json DELETE "/api/products/$($catalogProduct.id)" | Out-Null
    $aiMixedDraft = Invoke-AiEstimateUpload
    Assert-True (@($aiMixedDraft.prefill.lineItems).Count -ge 3) 'Mixed-source AI estimate intake did not create separate pasted-text and picture items.'
    Assert-True (@($aiMixedDraft.prefill.lineItems | Where-Object { $_.description -like 'Item from picture:*' }).Count -eq 1) 'Picture upload did not create a review line item in local fallback mode.'
    $aiDocumentDraft = Invoke-AiEstimateDocumentUpload
    Assert-True ($aiDocumentDraft.prefill.projectDescription -like '*Acceptance DOCX Customer*') 'DOCX source text was not extracted into the AI estimate draft.'
    Assert-True ($aiDocumentDraft.prefill.projectDescription -like '*PDF custom sign request*') 'PDF source text was not extracted into the AI estimate draft.'
    $aiBlockedUrlDraft = Invoke-Json POST '/api/ai/estimate-draft' @{
        sourceName = 'blocked URL safety test'
        sourceText = 'One custom bracket'
        sourceUrls = @('https://localhost/private-product')
    }
    Assert-True (@($aiBlockedUrlDraft.warnings | Where-Object { $_ -like '*public HTTPS pages only*' }).Count -eq 1) 'AI estimate intake did not disclose that a private/local URL was blocked.'
    $aiReviewStatus = Invoke-Json GET '/api/ai/review/status'
    Assert-True ($aiReviewStatus.sendsDataToAiProvider -eq $false) 'AI review status did not disclose that local review stays local.'
    Assert-True ($aiReviewStatus.safety -like '*Read-only*') 'AI review status did not disclose its read-only safety boundary.'
    $aiReview = Invoke-Json GET '/api/ai/review'
    Assert-True ($aiReview.engine -like '*Local rules*') 'AI review did not identify its engine.'
    Assert-True ($aiReview.safety -like '*Read-only*') 'AI review did not identify its safety boundary.'

    Write-Step 'Checking admin/config endpoints'
    $config = Invoke-Json GET '/api/config'
    $config.businessName = 'EPATA Acceptance Ledger'
    $config.calcMinimum = 18
    $savedConfig = Invoke-Json PUT '/api/config' $config
    Assert-True ($savedConfig.businessName -eq 'EPATA Acceptance Ledger') 'Config save did not persist businessName.'
    $clearFailure = Invoke-Raw POST '/api/database/clear'
    Assert-True ($clearFailure.StatusCode -eq 400) 'Database clear should be blocked.'

    Write-Step 'Checking generic ledger CRUD routes'
    $party = Assert-CrudRoundTrip 'parties' @{ name='Acceptance Customer'; partyType='Both'; email='customer@example.test'; phone='973-555-0101'; city='Testville'; state='NJ'; country='United States'; notes='acceptance' } 'notes' 'updated party'
    Assert-CrudRoundTrip 'products' @{ name='Acceptance Product'; sku='ACC-001'; category='3D Printed Product'; material='PLA'; color='Black'; grams=-10; materialCostPerGram=-0.1; printHours=2; machineRatePerHour=3; packagingCost=-1; designMinutes=20; targetPrice=-5; notes='acceptance' } 'notes' 'updated product' | Out-Null
    Assert-CrudRoundTrip 'customer-jobs' @{ jobDate='2026-05-30'; customerName='Acceptance Customer'; platform='Direct'; jobNumber='JOB-ACC-001'; relatedInvoiceNumber='INV-ACC-001'; jobName='Acceptance Job'; jobType='Print'; status='Open'; productName='Acceptance Product'; material='PLA'; color='Black'; quoteAmount=-25; invoiceAmount=-40; amountPaid=-10; notes='acceptance' } 'status' 'Completed' | Out-Null
    $sale = Assert-CrudRoundTrip 'sales' @{ saleDate='2026-05-30'; platform='Direct'; paymentMethod='Credit Card'; salesTaxHandling='Seller Collected'; orderNumber='ORD-ACC-001'; invoiceNumber=''; customerName='Acceptance Customer'; productName='Acceptance Product'; quantity=-1; itemSales=80; shippingCharged=5; salesTaxCollected=6.8; customerPaid=999; platformFees=-3; shippingLabelCost=-2; refunds=-4; estimatedCogs=-5; status='Paid'; includeInDashboard=$true; notes='acceptance' } 'notes' 'updated sale'
    Assert-Close ([decimal]$sale.customerPaid) 91.8 0.01 'Sale CRUD customer paid should be normalized.'
    Assert-CrudRoundTrip 'receivable-invoices' @{ invoiceNumber='AR-ACC-001'; invoiceDate='2026-05-30'; dueDate='2026-06-15'; customerName='Acceptance Customer'; projectName='AR Project'; status='Partial'; subtotal=100; discount=-12; rushFee=-4; taxRatePercent=10; salesTax=-7; invoiceTotal=1; amountPaid=-2; includeInCashReports=$true; notes='acceptance' } 'status' 'Paid' | Out-Null
    $bill = Assert-CrudRoundTrip 'bills' @{ vendorName='Acceptance Vendor'; billNumber='BILL-ACC-001'; billDate='2026-05-30'; dueDate='2026-06-30'; category='Supplies'; description='Acceptance bill'; amount=100; salesTax=7; total=1; amountPaid=-8; status='Partial'; paymentAccount='Checking'; taxDeductible=$true; notes='acceptance' } 'status' 'Paid'
    Assert-Close ([decimal]$bill.total) 107 0.01 'Bill total should normalize amount plus tax.'
    $expense = Assert-CrudRoundTrip 'expenses' @{ expenseDate='2026-05-30'; vendorName='Acceptance Vendor'; category='Supplies'; taxCategory='COGS / materials'; description='Acceptance expense'; paymentAccount='Checking'; amount=20; salesTax=2; total=1; receiptProof='proof'; taxBucket='COGS/Materials'; deductibleStatus='Yes'; businessUsePercent=150; countedExpense=$true; taxDeductible=$true; notes='acceptance' } 'notes' 'updated expense'
    Assert-Close ([decimal]$expense.total) 22 0.01 'Expense total should normalize amount plus tax.'
    Assert-Close ([decimal]$expense.businessUsePercent) 100 0.01 'Expense business use should clamp at 100.'
    Assert-CrudRoundTrip 'assets' @{ name='Acceptance Printer'; purchaseDate='2026-05-30'; vendorName='Bambu'; category='Equipment'; cost=-200; serialNumber='ACC123'; businessUsePercent=150; inServiceDate='2026-05-30'; taxTreatment='Section 179'; countedExpenseThisYear=$true; notes='acceptance' } 'notes' 'updated asset' | Out-Null
    Assert-CrudRoundTrip 'makerworld-rewards' @{ rewardDate='2026-05-30'; rewardType='Gift Card'; pointsChange=-100; giftCardAmount=-50; codeLast4='1234'; status='Available'; incomeStatus='Yes - Count as income'; notes='acceptance' } 'notes' 'updated makerworld' | Out-Null
    Assert-CrudRoundTrip 'audit-documents' @{ documentDate='2026-05-30'; documentType='Receipt'; relatedRecordType='Expense'; relatedRecordNumber='EXP-ACC'; fileName='acceptance.pdf'; filePathOrUrl='C:\acceptance.pdf'; notes='acceptance' } 'notes' 'updated audit doc' | Out-Null
    Assert-CrudRoundTrip 'business-accounts' @{ name='Acceptance Checking'; accountType='Checking'; institution='Acceptance Bank'; last4='1111'; openingBalance=-10; currentBalance=-5; isActive=$true; notes='acceptance' } 'notes' 'updated account' | Out-Null
    Assert-CrudRoundTrip 'action-items' @{ title='Acceptance action'; area='Tax'; priority='High'; dueDate='2026-06-01'; status='Open'; relatedRecord='ACC'; notes='acceptance' } 'status' 'Done' | Out-Null
    Assert-CrudRoundTrip 'tax-obligations' @{ taxYear=2026; title='Acceptance tax obligation'; jurisdiction='Federal'; obligationType='Estimated Income Tax'; formName='1040-ES'; period='Q2'; dueDate='2026-06-15'; status='Review Applicability'; estimatedAmount=-20; amountPaid=-10; appliesIf='Acceptance'; needsReview=$true; notes='acceptance' } 'status' 'Filed / Paid' | Out-Null
    Assert-CrudRoundTrip 'mileage-logs' @{ tripDate='2026-05-30'; vehicle='Acceptance Vehicle'; startLocation='Home'; endLocation='Post Office'; businessPurpose='Ship customer order'; businessMiles=-12; parkingAndTolls=-2; proofReference='calendar'; notes='acceptance' } 'notes' 'updated mileage' | Out-Null
    Assert-CrudRoundTrip 'settings' @{ key='AcceptanceSetting'; value='One'; notes='acceptance' } 'value' 'Two' | Out-Null

    Write-Step 'Checking proof/document intake upload'
    $upload = Upload-ProofFile
    Assert-True ($upload.count -eq 1) 'Document upload did not create one audit document.'
    Assert-True ($upload.documents[0].id -gt 0) 'Document upload did not return an audit document id.'
    Assert-True ($upload.documents[0].fileName -eq 'acceptance-upload-proof.txt') 'Document upload returned the wrong filename.'
    Assert-True ($upload.suggestions[0].engine -eq 'Local rules') 'Document suggestion did not identify its local-rules engine.'
    Assert-True ($upload.suggestions[0].usedAi -eq $false) 'Document suggestion incorrectly claimed model AI use.'
    Assert-True ($upload.suggestions[0].doesNot -like '*Does not create or save*') 'Document suggestion did not disclose its write boundary.'

    Write-Step 'Checking estimate and invoice builder workflows'
    $nextEstimate = Invoke-Json GET '/api/documents/next-number?type=ESTIMATE'
    Assert-True ($nextEstimate.number -like 'EST-*') 'Next estimate number should be EST-*.' 
    $estimate = Invoke-Json POST '/api/documents' (New-DocPayload 'ESTIMATE' 'Sent' $nextEstimate.number 500 'Acceptance Estimate Customer')
    Assert-EstimateMoney $estimate 'Estimate create'

    $duplicate = Invoke-Json POST "/api/documents/$($estimate.id)/duplicate"
    Assert-True ($duplicate.id -ne $estimate.id) 'Document duplicate reused source id.'
    Assert-True ($duplicate.docType -eq 'ESTIMATE') 'Estimate duplicate changed doc type.'
    Assert-EstimateMoney $duplicate 'Estimate duplicate'

    $invoiceFromEstimate = Invoke-Json POST "/api/invoice-documents/$($estimate.id)/convert-to-invoice"
    Assert-True ($invoiceFromEstimate.docType -eq 'INVOICE') 'Convert to invoice did not change doc type.'
    Assert-True ($invoiceFromEstimate.docNumber -like 'INV-*') 'Convert to invoice did not assign INV number.'
    Assert-DocMoney $invoiceFromEstimate 0 'Converted invoice'

    $nextInvoice = Invoke-Json GET '/api/invoice-documents/next-number?type=INVOICE'
    Assert-True ($nextInvoice.number -like 'INV-*') 'Next invoice number should be INV-*.' 
    $paidInvoice = Invoke-Json POST '/api/invoice-documents' (New-DocPayload 'INVOICE' 'Paid' $nextInvoice.number 110 'Acceptance Paid Customer')
    Assert-DocMoney $paidInvoice 110 'Paid invoice create'

    $sales = Invoke-Json GET '/api/sales?includeArchived=true'
    $paidSale = @($sales | Where-Object { $_.invoiceNumber -eq $paidInvoice.docNumber })[0]
    Assert-True ($null -ne $paidSale) 'Paid invoice did not sync to Sales.'
    Assert-Close ([decimal]$paidSale.itemSales) 100 0.01 'Paid invoice sale item sales allocation'
    Assert-Close ([decimal]$paidSale.salesTaxCollected) 10 0.01 'Paid invoice sale tax allocation'
    Assert-Close ([decimal]$paidSale.customerPaid) 110 0.01 'Paid invoice sale customer paid'
    Assert-True ($paidSale.paymentMethod -eq 'Zelle') 'Paid invoice payment method did not sync to Sales.'

    $arRows = Invoke-Json GET '/api/receivable-invoices?includeArchived=true'
    $paidAr = @($arRows | Where-Object { $_.invoiceNumber -eq $paidInvoice.docNumber })[0]
    Assert-True ($null -ne $paidAr) 'Paid invoice did not sync to AR.'
    Assert-Close ([decimal]$paidAr.invoiceTotal) 110 0.01 'Paid invoice AR total'
    Assert-Close ([decimal]$paidAr.amountPaid) 110 0.01 'Paid invoice AR paid'

    $partialPayload = New-DocPayload 'INVOICE' 'Partial' 'INV-ACC-PARTIAL' 55 'Acceptance Partial Customer'
    $partialInvoice = Invoke-Json POST '/api/documents' $partialPayload
    Assert-DocMoney $partialInvoice 55 'Partial invoice create'
    $sales = Invoke-Json GET '/api/sales?includeArchived=true'
    $partialSale = @($sales | Where-Object { $_.invoiceNumber -eq $partialInvoice.docNumber })[0]
    Assert-Close ([decimal]$partialSale.itemSales) 50 0.01 'Partial invoice sale item sales allocation'
    Assert-Close ([decimal]$partialSale.salesTaxCollected) 5 0.01 'Partial invoice sale tax allocation'
    Assert-Close ([decimal]$partialSale.customerPaid) 55 0.01 'Partial invoice sale paid'

    $partialPayload.status = 'Void'
    $partialPayload.amountPaid = 0
    $voidInvoice = Invoke-Json PUT "/api/documents/$($partialInvoice.id)" $partialPayload
    Assert-Close ([decimal]$voidInvoice.amountPaid) 0 0.01 'Void invoice paid should be zero.'
    $sales = Invoke-Json GET '/api/sales?includeArchived=true'
    $voidSale = @($sales | Where-Object { $_.invoiceNumber -eq $partialInvoice.docNumber })[0]
    Assert-True ($voidSale.includeInDashboard -eq $false) 'Voiding invoice should hide synced Sale from dashboard.'

    Invoke-Json DELETE "/api/documents/$($duplicate.id)" | Out-Null
    $arRows = Invoke-Json GET '/api/receivable-invoices?includeArchived=true'
    Assert-True (-not (@($arRows | Where-Object { $_.invoiceNumber -eq $duplicate.docNumber -and -not $_.isArchived }).Count)) 'Deleted duplicate left active AR rows.'

    Invoke-Json GET '/api/documents/latest' | Out-Null
    $stats = Invoke-Json GET '/api/documents/stats'
    Assert-True ($stats.totalInvoices -ge 3) 'Document stats did not count created invoices.'
    Assert-True ($stats.totalInvoiced -ge 110) 'Document stats did not include active invoice totals.'

    Write-Step 'Checking legacy import failure path is clean'
    $legacy = Invoke-Json POST '/api/invoice-documents/import-from-legacy'
    Assert-True ($legacy.success -eq $false) 'Legacy import without old app should fail gracefully, not claim success.'

    Write-Step 'Checking exports and backups'
    foreach ($entity in @('parties', 'sales', 'customer-jobs', 'receivable-invoices', 'bills', 'expenses', 'products', 'assets', 'makerworld-rewards', 'audit-documents', 'business-accounts', 'action-items', 'tax-obligations', 'mileage-logs')) {
        $csv = Invoke-Raw GET "/api/export/$entity"
        Assert-True ($csv.StatusCode -eq 200) "CSV export failed for $entity."
        Assert-True ($csv.Content.Length -gt 10) "CSV export for $entity looked empty."
    }
    foreach ($group in @('all', 'noncash', 'digital', 'card', 'online', 'cash', 'other', 'unknown')) {
        $csv = Invoke-Raw GET "/api/export/tax-sales?paymentGroup=$group"
        Assert-True ($csv.StatusCode -eq 200) "Tax sales export failed for payment group $group."
        Assert-True ($csv.Content -like '*PaymentGroup*') "Tax sales export for $group did not include PaymentGroup."
    }
    $digitalTaxCsv = Invoke-Raw GET '/api/export/tax-sales?paymentGroup=digital'
    Assert-True ($digitalTaxCsv.Content -like '*Zelle*') 'Digital-transfer tax export did not include the paid Zelle invoice.'
    $cardTaxCsv = Invoke-Raw GET '/api/export/tax-sales?paymentGroup=card'
    Assert-True ($cardTaxCsv.Content -like '*Credit Card*') 'Card tax export did not include the credit-card sale.'
    $njSalesTaxCsv = Invoke-Raw GET '/api/export/nj-sales-tax?year=2026'
    Assert-True ($njSalesTaxCsv.StatusCode -eq 200) 'NJ sales-tax review export failed.'
    Assert-True ($njSalesTaxCsv.Content -like '*Seller Collected*') 'NJ sales-tax review export did not include seller-collected handling.'
    $taxSummaryCsv = Invoke-Raw GET '/api/export/tax-summary?year=2026'
    Assert-True ($taxSummaryCsv.Content -like '*WorkingNetProfit*') 'Tax summary export did not include working net profit.'
    $taxPackage = Invoke-Raw GET '/api/export/tax-package?year=2026'
    Assert-True ($taxPackage.StatusCode -eq 200) 'Tax package ZIP export failed.'
    Assert-True ($taxPackage.Content.Length -gt 500) 'Tax package ZIP looked empty.'
    $backup = Invoke-Raw GET '/api/database/backup'
    Assert-True ($backup.StatusCode -eq 200) 'Database backup endpoint failed.'
    $systemBackup = Invoke-Raw POST '/api/system/backup'
    Assert-True ($systemBackup.StatusCode -eq 200) 'System backup endpoint failed.'
    Assert-True ($systemBackup.Content.Length -gt 100) 'System backup response looked empty.'

    Write-Step 'Checking dashboard and tax calculation outputs'
    $dashboard = Invoke-Json GET '/api/dashboard'
    Assert-True ($dashboard.kpis.grossReceipts -gt 0) 'Dashboard gross receipts should reflect acceptance sales.'
    Assert-True ($dashboard.kpis.estimatedNet -ne $null) 'Dashboard estimatedNet missing.'
    $taxAudit = Invoke-Json GET '/api/tax-audit'
    Assert-True ($null -ne $taxAudit.summary) 'Tax audit summary missing.'
    $highTaxIssues = @($taxAudit.issues | Where-Object { $_.severity -eq 'High' })
    if ($highTaxIssues.Count -gt 0) {
        Write-Host '[acceptance] High tax issues:'
        $highTaxIssues | ConvertTo-Json -Depth 5 | Write-Host
    }
    Assert-True ($highTaxIssues.Count -eq 0) 'Tax audit has high severity issues in disposable acceptance DB.'

    Write-Step 'Checking API aliases agree'
    $docsA = Invoke-Json GET '/api/documents'
    $docsB = Invoke-Json GET '/api/invoice-documents'
    Assert-True (@($docsA).Count -eq @($docsB).Count) 'Documents and invoice-documents aliases returned different counts.'

    Write-Step 'Acceptance suite passed'
} catch {
    if ($serverJob) {
        $jobOutput = Receive-Job -Job $serverJob -Keep -ErrorAction SilentlyContinue
        if ($jobOutput) {
            Write-Host '[acceptance] Server output before failure:'
            Write-Host $jobOutput
        }
    }
    throw
} finally {
    if ($serverJob) {
        Stop-Job -Job $serverJob -ErrorAction SilentlyContinue | Out-Null
        Receive-Job -Job $serverJob -ErrorAction SilentlyContinue | Out-Null
        Remove-Job -Job $serverJob -Force -ErrorAction SilentlyContinue | Out-Null
    }

    foreach ($path in @($uploadProbe, $aiDocxProbe, $aiPdfProbe)) {
        if (Test-Path -LiteralPath $path) {
            Remove-Item -LiteralPath $path -Force
        }
    }
    Get-ChildItem -LiteralPath (Join-Path $root 'UploadedDocs') -Filter '*acceptance-upload-proof.txt' -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue
}
